name: First Action - Single

on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo "Hello world!"

  hello-world2:
    runs-on: ubuntu-latest
    steps:
      - name: First step2
        run: echo "bye world!"

  new-job:
    runs-on: ubuntu-latest
    steps:
      - name: Third step
        run: echo "This is the new job!"