name: First Action - Single

on:
  workflow_dispatch:
    inputs:
      debug_mode:
        type: boolean
        description: Debug
        default: false
        required: false
      sample_value:
        type: string
        description: Cualquier valor
        default: ""
        required: false

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: First step
        run: echo "Hello world!"
  new-job:
    runs-on: ubuntu-latest
    needs: hello-world
    steps:
      - name: first-step
        run: echo "hello world!"
      - name: second-step
        run: echo ${{ github.event.inputs.debug_mode }}
